### ISSUE TITLE
Using Transpiled FFI Source 

### ISSUE THREAD

**Issue by seanstrom** [ethul/purescript-webpack-plugin#26]
Hi :smile:
I'm wondering if it's possible to configure Webpack and this plugin to use ES6 source as the FFI files. I know ES6 isn't natively supported, but can the compiled source be passed to the plugin?

Tag: @ethul

**Comment by ethul** [comment]
I think this would be a great feature to have. Currently however, the FFI files require ES5. I will have to think more about if there might be away to get `psc` to pickup the output of a webpack loader. I gave it a quick go, but didn't seem to get it to work out. I am open to idea on this though.

**Comment by seanstrom** [comment]
Yeah it doesn't appear obvious how we'll be able to obtain the compiled js from webpack... :cry: 
On top of that `psc` want a list of files to retrieve, so it seems I may need a temporary directory. I could use a task runner (gulp) and put the compiled files in another directory, then I could glob those files and pass them to the webpack plugin. Wish I had a more self contained way of doing that though :smile:
