### ISSUE TITLE
Make psc-bundle step optional

### ISSUE THREAD

**Issue by natefaubion** [ethul/purescript-webpack-plugin#9]
I don't really need this for normal dev, and it can take a long time since its a whole program optimization that must run for every change. Can we make it optional?

**Comment by ethul** [comment]
I think this would be a good option to add. I've been thinking about the same thing. Also, we can maybe use the new source maps feature in [0.8.2](https://github.com/purescript/purescript/releases/tag/v0.8.2) without the bundle step.

**Comment by ethul** [comment]
Supported in `purs-loader@0.6.0-beta.4` and `purescript-webpack-plugin@0.2.0-beta.5`

**Comment by ethul** [comment]
I've bumped the beta versions of the loader and plugin, and added an example in case it helps:
https://github.com/ethul/purescript-webpack-example
